### PR TITLE
Basic block support

### PR DESCRIPTION
**Pull request by yshewchuk**
Adding basic block support, will possibly add more as needed. Let me know if I've done something strange, I'm not very experienced with git or github. 

I'm not sure if it will matter, but blocks should have slightly different code depending on the context that they are in. For example, if a block is the body of an Expression<Action> it will not have a return statement, but if it's the body of an Expression<Func<T>> it will. This difference can be avoided by always explicitly setting the resultant type of the block, but it would be nice if it behaved similarly to the compilation. 
ie: 
var p = Expression.Parameter(typeof(int), "p");
var assign = Expression.Assign(p, Expression.Constant(1));
var block = Expression.Block(new ParameterExpression[] { p }, assign);
var lambda = Expression.Lambda<Action<int>>(block);

// this would compile such as (p => { p = 1; }) but when converted to code through the lib would currently give "p => { return p = 1; }"

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
Looks good!

**Comment by EamonNerbonne** [comment]
And released as 1.5.1!

**Comment by EamonNerbonne** [comment]
And I'm doing this in the wrong order, but could you confirm that you license your changes under the Apache 2.0 license to me?

**Comment by yshewchuk** [comment]
You're absolutely right about the 'efficiency' I don't know why I even mentioned it. Sometimes I get a bit caught up in the theoretical, I guess. Also, yes I license my contributions to you :)

**Pull request merged**
