### PR TITLE
- added most 'new' test

### PR DESCRIPTION
**Pull request by asd-and-Rizzo**
- made sure test class is visible for all IDE runners
- renamed one test for more proper
- added git ignore for binaries	 
- experimenting with Roslyn to go for extended generation and printin… …

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
I'd love to merge some (or all) of this, but I don't quite understand what you're doing.  It would be helpful to have smaller, single-purpose pull requests.

I *really* love the idea of replacing the current ExpressionToCode backend with a Roslyn syntax tree; however I don't currently have time for that alas.  This might also finally allow a simple implementation of correct generic type parameter elision; I'm assuming Roslyn has code for overload resolution in any case...

Some specific questions:

 - "made sure test class is visible for all IDE runners"  What did you change; for which IDE runners is this required (SharpDevelop I gather?) and why is this necessary?  Can you split this into a seperate pull request?

 - the git ignore and test rename are fine.  Please however place the new "NewObject" test next to the old one (rather than at the bottom of the file) so it's a little easier to navigate this (already too-long) file.

What's "added test to show functional quickly instead of going to PAssert" for?

Finally: do you agree to license your changes (and all future pull requests you contribute to in this repository) to me under the Apache 2.0 license?

**Comment by asd-and-Rizzo** [comment]
For some reason pull request are auto added to first in TortoiseGit. Do not get why. Will split.

"made sure test class is visible for all IDE runners" - SharpDevelop does not see test class and no run test button until I added [TestFixture]

"NewObject" will move closed to previous.

"added test to show functional quickly instead of going to PAssert" for?" I searched what is meaning of AnnotatedToCode, so wrote quick test. I think at leas one test should be to show idea without resorting to PAssert. "ToAnnotatedCode" is better name. 

"do you agree to license your changes (and all future pull requests you contribute to in this repository) to me under the Apache 2.0 license?" Ok, agree. But suggest do not bother and go https://creativecommons.org/publicdomain/zero/1.0/ or like in free to do any with code(seems MIT is such).  Actually first implementation of Expression to Roslyn Syntax Tree may doom future of this lib, and some person will not want to bother with Apache and implement on own. There are other reasons either, like all project .net of such small side did not brought much to initial developers cause where redeveloped or even never feed backed any code back.

Regarding Roslyn, what is error you are talking about Roslyn may fix? Is there failing unit test for this?

As of now, there you use custom visitor for tree, why not default of `ExpressionVisitor'`? Some limitations?

Right now I just hacked Roslyn to parse ExpressionToCode output. But seems ExpressionToCode should provide more generic visitor, dumping stuff in one case into string, in other into Roslyn Syntax Tree, in third case it should dump references assemblies Expression out of expressions to allow later compilation (I.e. preserve this info).

**Comment by EamonNerbonne** [comment]
The Apache 2.0 license is compatible with the MIT license. IIRC the only meaningful difference is that it explicitly mentions that you're granted a patent grant too (not that I assume anyone has patents on this stuff...)

**Comment by EamonNerbonne** [comment]
On ExpressionVisitor: There's no particularly strong reason; but I can't see the advantage.  You still need to manually dispatch node types (which I'm using a T4 template for now), and the default visitor has an `Expression` return type, but that's not what I want (and if the default implementation actually does anything with that it's just a waste of CPU cycles.  Also, it doesn't support any post .net 3.5 features (like expression.assign).

I think in essence the issue is that the standard class simply adds complexity but no value.  If there were some value, we could switch....

**Comment by EamonNerbonne** [comment]
On describing AnnotatedToCode: You're right, it's completely undocumented - that's not good...

It should be in the README, and all these methods should have doc-comments. The unit test is a good one too.  Good catch!

**Comment by EamonNerbonne** [comment]
I'm going to close this PR; if you've split it up, please open new ones!

**Pull request closed without merging**
