### PR TITLE
Use fast-expression-compiler via nuget

### LINKED ISSUE #66: Use the FastExpressionCompiler package
Hi @EamonNerbonne,

I've found some time to make an optimized expression compiler into standalone project as [FastExpressionCompiler](https://github.com/dadhi/FastExpressionCompiler).

Current version is [1.0.0-preview-01](https://www.nuget.org/packages/FastExpressionCompiler/1.0.0-preview-01). But it is pretty stable overall and used in [DryIoc v2](https://bitbucket.org/dadhi/dryioc).

__What was added:__

- Support for .NET Core via NetStandard1.3
- Support for nested lambdas and closures, so the majority of expression types should be covered
- Improved performance :-) as usual

### PR DESCRIPTION
**Pull request by EamonNerbonne**
(Resolves #66 )

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
Unfortunately, this isn't any faster yet for the benchmarked expression:

```C#
            var x = 1;
            var s = "Test";
            return () => x == 1 && (s.Contains("S") || s.Contains("s"));
```

Results:
```
Total time: 00:00:32 (32.96 sec)

// * Summary *

BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4770K CPU 3.50GHz, ProcessorCount=8
Frequency=3421924 Hz, Resolution=292.2333 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0


                  Method |            Mean |        StdDev |
------------------------ |---------------- |-------------- |
             JustCompile | 391,929.7514 ns | 1,863.7288 ns |
         JustFastCompile | 406,503.5805 ns | 4,829.6535 ns |
      PAssertWithCompile | 399,197.3278 ns | 2,854.7275 ns |
  PAssertWithFastCompile | 411,837.6719 ns | 2,744.0544 ns |
 BaseLinePlainLambdaExec |     119.5885 ns |     0.5521 ns |

*** Hints ***
Outliers
  BenchmarkPAssert.JustCompile: Default             -> 1 outlier  was  removed
  BenchmarkPAssert.JustFastCompile: Default         -> 1 outlier  was  removed
  BenchmarkPAssert.BaseLinePlainLambdaExec: Default -> 1 outlier  was  removed
```

**Comment by dadhi** [comment]
Mmm, I think this is Ok. The expression is the simple one. It may be also different for different platforms.

**Comment by dadhi** [comment]
Hey, may be it is falling back to default Expr.Compile, no?

**Comment by dadhi** [comment]
So yes, it is. `And, AndAlso, Or`, etc. is not supported yet. Should not take long to add, I hope. Explains the benchmark results.

**Comment by EamonNerbonne** [comment]
Fine!

**Comment by EamonNerbonne** [comment]
(I'm not too worried about limited expression support; after all, it's almost certainly still better than nothing!)

**Pull request merged**
