### PR TITLE
- made namespace for easily for importing and like in other projects

### PR DESCRIPTION
**Pull request by asd-and-Rizzo**

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
The hope is to improve this api until it's ready for prime time  rather than encourage usage.  I mean, it's fine for people like you who are intimately familiar with it, but I actively don't want people to depend on an API that I'm likely to break.

**Comment by EamonNerbonne** [comment]
I've merged this and named the namespace `Unstable_Experimental_Api`.  It's released to nuget as version 2.0.0-alpha2.

Since these classes have been lying around for quite some time... If you happen to have a link to a bit of code where you want to use them, that would be great!

I'd like to finalize the api for v2, so I'm trying to figure out what use cases are.

**Comment by dadhi** [comment]
Here is the reference to usage in DryIocZero https://bitbucket.org/dadhi/dryioc/src/be25dd5200e4415d116ca100d6769b63627408e1/Net45/DryIocZero/Container.Generated.tt?at=default

It is a normal API. But just in case.

**Comment by EamonNerbonne** [comment]
Thanks, I'll take a look!

**Comment by asd-and-Rizzo** [comment]
We use `ToNameOf	` as adhoc 'schema mapping`, `projection` and `simple filters` to query `ElasticSearch` in strongly typed manner.

E.g. next query converted into strings and JSON:

```
	var files= this.myAuditRepository.GetFiles(
				storageId,
                                f => f.FileId,// group by
				f => f.FileId,// get next fields and omit anything not mentioned
				f => f.Change,
				f => f.StorageId,
				f => f.Timestamp)

```

We do not have full LINQ provider with recursive Expressions parsing and use `ToNameOf` as solution.

**Pull request merged**
