### PR TITLE
Use xunit

### PR DESCRIPTION
**Pull request by EamonNerbonne**

### CODE REVIEW

**Comment by dadhi** [comment]
Hello, Just curious why did you decide to switch given the tedious work to do so. I see that XUnit is more succinct, less noisy. Anything else to consider?

**Comment by EamonNerbonne** [comment]
Hi @dadhi! I switched because I'm not entirely happy with certain aspects of nunit and wanted to give xUnit.net 2 a shot - and `ExpressionToCode` is relatively small and self contained so a reasonable candidate to get your toes wet.

Aside on issues with nunit v2:

In a work project using NUnit I've noticed that the way setups, teardowns (and fixture setups+teardowns) interact with inheritance leads to difficult to follow tests.  xUnit uses more conventional construct/dispose semantics, and is thus more amenable to convential reasoning about classes.  Also, nunit supports TestCases and TestCaseSources, and these are great, but they're not statically typed, which makes test maintenance in a long-running project a burden - refactoring can't rely on the type-system.  On a more fundamental level, C# already has numerous looping methods available, and there's no particular need for yet another (`TestCaseSource`).  As a side effect of reimplementing looping, you get all the issues with an unpolished implementation, such as poor tooling, a learning curve, and performance issues. Test case discovery on a large test set is noticably slow in nunit, and that's a problem because it means that you can't iterate quickly.  I profiled nunit, and the problems in v2 look pretty fundamental.  Even if nunit test case discovery were fixed, because nunit needs to enumerate all test case sources before running a single test, that means that just one poorly implemented testcasesource can bottleneck running a completely unrelated test.

Lack of static typing is also an issue with NUnit's fluent `Assert.That` - in fact, that was kind of the point of `ExpressionToCode` originally.

I looked in some depth into nunits internals, but the test-case discovery really isn't pluggable, so you're out of luck.  xunit 1 was pluggable, but it was a hassle - the api looks like pluggability was mostly an accident of overly generic code, rather than really friendly to extension.

By contrast, xunit 2 has a really simple extensibility point for implementing the likes of `TestCaseSource` - [`IXunitTestCaseDiscoverer`](https://github.com/xunit/xunit/blob/master/src/xunit.core/Sdk/IXunitTestCaseDiscoverer.cs). With that, you might implement a normal collection-returning method, leaving it up to the test other to prefer linq or `yield return` or whatever, and allowing conventional tooling to deal with them better.

I do intend to give nunit 3 a shot; but xunit 2 is available now.

Results so far: xunit 2 is slower than nunit 2 in ExpressionToCode.  Then again, all these tests are fast and there aren't that many, so we're talking 0.5 seconds vs. 1.5 seconds to run everything.

**Comment by dadhi** [comment]
That's a detailed answer, worse it's own post XD. Thank you!

I have 700+ NUnit tests in DryIoc, and observing recent tendency to switch to XUnit - wandered why. 

Given all other things, for me execution speed is important because I am running tests continuously with [NCrunch](http://www.ncrunch.net/).

Currently I am not using TestCases, though the may fit in future. And no Initialize/Teardown either, I like my tests to be independent as much as possible to move them around.

Probably will look more into NUnit3 vs NUnit2 vs XUnit comparison.. And check for automatic conversation solutions if available.

**Comment by EamonNerbonne** [comment]
I'm not sure if the performance issue is a general startup cost or systematic.  One thing that does offset it is that xunit tests in parallel by default (you can of course influence that in various ways, but that's the default).

**Pull request merged**
