### PR TITLE
Move public api changes to unstable ns

### PR DESCRIPTION
**Pull request by EamonNerbonne**

### CODE REVIEW

**Comment by dadhi** [comment]
Looks good. Are you planning to move IObjectToCode as well?

**Comment by EamonNerbonne** [comment]
Yeah.  I'm pretty sure I'm going to want to configure more, and perhaps naming could be improved too.  But that's going to take time, so I want the freedom to experiment a bit :-)

**Comment by EamonNerbonne** [comment]
For example, I'm pretty sure a good solution to #47 (`typeof(List<>)` support) would be to add a config option to `ObjectToCode` to simply generate the empty string for unbound generic type arguments.

**Comment by dadhi** [comment]
Yes, make sense.

**Comment by EamonNerbonne** [comment]
Pushed to nuget as 1.5.0 :-) - I'm calling it a weekend; cya!

**Comment by dadhi** [comment]
Great news! I will give it a try with DryIoc next week. Thank you.

**Pull request merged**
